# Generated by Django 3.0.7 on 2021-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20210401_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=6, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
