# Generated by Django 3.0.7 on 2021-04-01 13:51

from django.db import migrations

from foodcartapp.models import OrderProducts, Product


def replace_fake_price(apps, schema_editor):
    OrderProducts = apps.get_model('foodcartapp', 'OrderProducts')
    Product = apps.get_model('foodcartapp', 'Product')

    orders_product = OrderProducts.objects.all()
    for order in orders_product:
        product_price = \
            Product.objects.get(name=order.product.name,
                                description=order.product.description).price
        order.product_price = product_price
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderproducts_product_price'),
    ]

    operations = [
        migrations.RunPython(replace_fake_price),
    ]
