# Generated by Django 3.0.7 on 2021-04-01 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20210401_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
